### ISSUE TITLE
Script not working on the Steam Deck

### ISSUE THREAD

**Issue by ghost** [fcorsino/gamesir-g3w-fix#1]
Same as title, the controller doesn't work on steam after using the code.
This is what appears on the terminal:
"--2022-11-12 13:07:28--  https://raw.githubusercontent.com/fcorsino/gamesir-g3w-fix/main/gamesir-g3w-fix-install.bash
SSL_INIT
Loaded CA certificate '/etc/ssl/certs/ca-certificates.crt'
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 2606:50c0:8000::154, 2606:50c0:8001::154, 2606:50c0:8002::154, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|2606:50c0:8000::154|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2225 (2.2K) [text/plain]
Saving to: ‘gamesir-g3w-fix-install.bash.1’

gamesir-g3w-fix-install.bas 100%[=========================================>]   2.17K  --.-KB/s    in 0s      

2022-11-12 13:07:29 (22.2 MB/s) - ‘gamesir-g3w-fix-install.bash.1’ saved [2225/2225]

which: no dpkg in (/usr/local/sbin:/usr/local/bin:/usr/bin:/var/lib/flatpak/exports/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl)
Installing pyusb with pip
sudo: pip: command not found"

**Comment by fcorsino** [comment]
Thanks for reporting this. The script tries to install some dependencies needed to run the code (namely pyusb). Looks like your system is not Debian, Ubuntu or one of its derivatives. Can you please confirm which distribution you are running? The script fails because it assumes python pip is already present and it is not. I may be able to integrate a fix for installing pip also on the script.

**Comment by ghost** [comment]
The distro is SteamOS 3.0, based on archlinux. Still not downloadable, there's only a recovery iso for the Steam Deck. The filesystem is read-only though, and any changes you make are removed every time there's a new update. I used 
[this post ](https://www.reddit.com/r/SteamDeck/comments/x4ct1r/how_do_i_do_a_pip3_install/) here to install pip3 into ~/.local/bin/ to bypass this, but now it says 
```
which: no dpkg in (/home/deck/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/var/lib/flatpak/exports/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl)
Installing pyusb with pip
Traceback (most recent call last):
File "/home/deck/.local/bin/pip", line 5, in <module>
from pip._internal.cli.main import main
ModuleNotFoundError: No module named 'pip'
```
dk if that's any useful. Also tried `python get-pip.py --user`. Didn't help.

**Comment by fcorsino** [comment]
I have updated the script to check if pip is not available and if it is not, check if it's an ArchLinux system and then try to install the package using pacman. 

The change is tested on a regular ArchLinux , however I do not know if this would work on the Steam Deck. Based on that post you referenced, looks like SteamOS does not come with pip installed and it is not straight forward to get it installed.

I would suggest that you first investigate how to make changes permanent on the SteamOS filesystem, as this script expects to be able to make changes in the udev rules. This is, even if you get pip available by one of those workarounds, you will still need to be able to make changes on the system.

**Comment by ghost** [comment]
I know of a way to disable the read-only filesystem, so I can use the package manager to install pip and run the script. Basically [this](https://www.reddit.com/r/SteamDeck/comments/t8al0i/install_arch_packages_on_your_steam_deck/), except that you add "holo" to populate archlinux, and you use steamos-readonly disable instead of sudo btrfs property set / ro false. 

But steam will still delete any changes in its favorite folders after an update, which probably include /usr and /etc. I think there's no way to make changes permanent, but someone suggested overlayfs or hombrew of linux might be a workaround...

**Comment by fcorsino** [comment]
I am closing this issue as it is a general problem with SteamOS and the specific solution is not the intent of this script.
